models/__init__.py
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from config import SQLALCHEMY_DATABASE_URI


class MyDB:
    DB_URI = SQLALCHEMY_DATABASE_URI

    def __init__(self):
        self.Base = sqlalchemy.orm.declarative_base()
        self.engine = create_engine(MyDB.DB_URI)
        self.create_tables()
        self.session = sessionmaker(bind=self.engine)()

    def create_tables(self):
        self.Base.metadata.create_all(self.engine)


db = MyDB()

models/user.py
from . import db
from sqlalchemy import Column, ForeignKey, Integer, String
from flask_login import UserMixin


class User(db.Base, UserMixin):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, autoincrement=True)
    email = Column(String(200), unique=True)
    name = Column(String(30), nullable=False, unique=True)
    password = Column(String(1000), nullable=False)


db.create_tables()

forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, EmailField, PasswordField


class LoginForm(FlaskForm):
    username = StringField(label='Username', validators=[validators.DataRequired('Enter your email or username')])
    password = PasswordField(label='Password', validators=[validators.DataRequired('Enter your password')])
    submit = SubmitField('Submit')

forms/reg_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, EmailField, PasswordField


class RegForm(FlaskForm):
    email = EmailField(label='Email', validators=[validators.DataRequired('Enter your email'),
                                                  validators.Email()])
    username = StringField(label='Username', validators=[validators.Length(max=30),
                                                         validators.DataRequired('Enter your username')])
    password = PasswordField(label='Password', validators=[validators.Length(min=5),
                                                         validators.DataRequired('Enter your password')])
    submit = SubmitField('Submit')

app.py
from flask import Flask, render_template, url_for

from controllers.users import login_manager
from models import db
from routes.chess_game_bp import chess_game_bp
from routes.users_bp import users_bp

app = Flask(__name__)
app.config.from_object('config')
app.register_blueprint(chess_game_bp)
app.register_blueprint(users_bp)
login_manager.init_app(app)
db.create_tables()


@app.route('/')
def home():
    return render_template('index.html')


if __name__ == '__main__':
    app.run(port=8000, debug=True)

controllers/chess_game.py
from flask import render_template, request, jsonify, flash
from flask_login import login_required

from chess import Chess

game_modes = [(1, 0), (2, 1), (3, 0), (3, 2), (5, 0), (5, 3), (10, 0), (10, 5), (15, 10), (30, 0), (30, 20)]
game = Chess()


@login_required
def play():
    return render_template('game_modes.html', modes=game_modes)


@login_required
def start_game():
    global game
    if request.method == 'GET':
        game = Chess()
        minutes = request.args.get('minutes')
        extra = request.args.get('extra')
        game.board.start_game()
        return render_template('board.html', game=game, mins=minutes, extra=extra)
    move_data = request.get_json()
    try:
        time_expired = move_data['time_expired']
    except KeyError:
        pass
    else:
        game.game_over = True
        if time_expired == 'White':
            game.winner = 'Black'
        else:
            game.winner = 'White'
        return jsonify({'success': False, 'game_over': game.game_over, 'winner': game.winner}), 200
    fig = game.board.get_fig(move_data['prevx'], move_data['prevy'])
    if fig is not None:
        fig = fig.my_copy()
    if game.game_over:
        res: bool = False
    else:
        res: bool = game.make_move(fig, move_data['curx'], move_data['cury'])
    return jsonify({'success': res, 'img': fig.image, 'game_over': game.game_over, 'winner': game.winner}), 200

controllers/users.py
from flask import request, render_template, redirect, url_for, flash
from flask_login import login_user, LoginManager, login_required, logout_user, current_user
from sqlalchemy import or_
from werkzeug.security import generate_password_hash, check_password_hash

from forms.login_form import LoginForm
from forms.reg_form import RegForm
from models import db
from models.user import User

login_manager = LoginManager()
login_manager.login_view = '/login'
login_manager.login_message = 'Please log in to access this page!'


@login_manager.user_loader
def load_user(user_id):
    user = db.session.query(User).filter(User.id == int(user_id)).first()
    if user:
        return user
    return None


def login():
    login_form = LoginForm()
    if request.method == 'GET':
        return render_template('login.html', login_form=login_form)
    if login_form.validate_on_submit():
        email_or_name = login_form.username.data
        password = login_form.password.data
        if '@' in email_or_name:
            cur_user = db.session.query(User).filter(User.email == email_or_name).first()
        else:
            cur_user = db.session.query(User).filter(User.name == email_or_name).first()
        if cur_user is None:
            flash('No such user!')
            return render_template('login.html', login_form=login_form)
        if check_password_hash(cur_user.password, password):
            login_user(cur_user)
            return redirect(url_for('home'))
        else:
            flash('Wrong password!')
            return render_template('login.html', login_form=login_form)


def register():
    reg_form = RegForm()
    if request.method == 'GET':
        return render_template('register.html', reg_form=reg_form)
    if reg_form.validate_on_submit():
        name = reg_form.username.data
        password = reg_form.password.data
        email = reg_form.email.data
        prev_user = db.session.query(User).filter(or_(User.email == email, User.name == name)).first()
        if prev_user is not None:
            flash('This user already exists!')
            return render_template('register.html', reg_form=reg_form)
        hashed_password = generate_password_hash(
            method="pbkdf2:sha256",
            salt_length=7,
            password=password
        )
        new_user = User(
            name=name,
            password=hashed_password,
            email=email
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('home'))


@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))

routes/chess_game_bp.py
from flask import Blueprint
from controllers.chess_game import play, start_game

chess_game_bp = Blueprint('chess_game_bp', __name__)
chess_game_bp.route('/play', methods=['GET', 'POST'])(play)
chess_game_bp.route('/game', methods=['GET', 'POST'])(start_game)
# chess_game_bp.route('/game', methods=['GET', 'POST'])(move)

routes/users_bp.py
from flask import Blueprint
from controllers.users import login, register, logout

users_bp = Blueprint('users_bp', __name__)
users_bp.route('/login', methods=['GET', 'POST'])(login)
users_bp.route('/register', methods=['GET', 'POST'])(register)
users_bp.route('/logout', methods=['GET'])(logout)

templates/board.html
{% extends "layout.html" %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block navbar %}
    {{ super() }}
{% endblock %}

{% block flash %}
    {{ super() }}
{% endblock %}

{% block content %}
<section id="game">
  <div>
    <div>
      <div class="player_up">
        <h2>Player Up</h2>
      </div>
      <div class="board">
        <table>
        {% for i in range(7, -1, -1): %}
          <tr>
          {% for j in range(0, 8, 1): %}
            {% if (i + j) % 2 == 0: %}
            {% set field_type = 'black' %}
            {% else: %}
            {% set field_type = 'white' %}
            {% endif %}
            <td class="field {{field_type}}" id="f{{j}}{{i}}">
              {% set fig = game.board.get_fig(j, i) %}
              {% if fig is not none: %}
<!--              <button class="figure">-->
                <div class="figure">
                  <img src="{{fig.image}}" width="100%" height="100%">
                </div>
<!--              </button>-->
              {% endif %}
            </td>
            {% endfor %}
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="player_down">
        <h2>Player Down</h2>
      </div>
    </div>
    <div class="timer">
      <div class="timer_up">
        <div>
          <h2>
            {{mins}}:{{extra}}
          </h2>
         </div>
      </div>
      <div class="timer_field">
        <h2></h2>
      </div>
      <div class="timer_down">
        <div>
          <h2>
            {{mins}}:{{extra}}
          </h2>
         </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

{% block js %}
  <script src="static/js/chess_game.js"></script>
{% endblock %}

templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel=”stylesheet” href=”https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css”>
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
</head>
<body>
  <button class="b">Dextar</button>

</body>
</html>

templates/footer.html
{% block footer %}
<footer class="bg-dark py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a class="btn button" href="#">Back to top ⬆</a>
      </p>
      <p class="mb-1">This website is strictly for educational purposes only!</p>
      <p class="mb-0">Made with 💛  by  <a href="https://github.com/Dextar713/">Dextar713</a> and <a href="https://github.com/whos-gabi/">whos-gabi</a>.</p>
    </div>
  </footer>
{% endblock %}

templates/game_modes.html
{% extends "layout.html" %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block navbar %}
    {{ super() }}
{% endblock %}

{% block flash %}
    {{ super() }}
{% endblock %}

{% block content %}
<section id="game_choice" class="p-5 m-5">
    <h1>Select Game Mode</h1>
        <div class="game_modes">
            {% for mode in modes %}
            <div>
                <a href="{{url_for('chess_game_bp.start_game', minutes=mode[0], extra=mode[1])}}" class="mode_btn">
                    <div class="card p-3 m-0">
                        <h1>
                            {{mode[0]}}m + {{mode[1]}}s
                        </h1>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
</section>
{% endblock %}

templates/header.html
{% block navbar %}
<section id="mynav">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('home')}}">
        <img src="static/img/Chess Pieces/WhiteKnight.png" height="35" alt="" class="mb-1">
        Chess of Fortune</a>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarCollapse">
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('chess_game_bp.play')}}"><i class="bi bi-play-fill"></i>Play</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Stats</a>
          </li> -->
          {% if not current_user.is_authenticated: %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users_bp.register')}}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users_bp.login')}}">Login</a>
          </li>
          {% else: %}
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="bi bi-person-circle"></i>              
              {{current_user.name}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users_bp.logout')}}"><i class="bi bi-box-arrow-right"></i>Logout </a>
          </li>
          {% endif %}
        </ul>

      </div>
    </div>
  </nav>
</section>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
{{ super() }}
{% endblock %}

{% block flash %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row p-5">
        <div class="d-flex align-items-center">
            <div class="col-md-6 p-5 align-i" data-aos="fade-right" data-aos-duration="900">

                <h1>Chess of Fortune</h1>
                <h3>SUCCESS IS LEARNT ♟️</h3>
                <p>In the multifaceted battle against The Matrix, you begin by becoming as rich as possible.</p>
                <a class="btn button d-block" href="/play">
                    <h4>Play NOW</h4>
                </a>
            </div>
            <div class="col-md-6" data-aos="fade-left" data-aos-duration="1500">
                <img src="static/img/chess-pawns.png" alt="">
            </div>
        </div>
    </div>

    <hr class="m-5">

    <div class="row p-5 d-flex align-items-center m-n3">
        <div class="col-md-4" data-aos="fade-right" data-aos-duration="1100">
            <img src="static/img/mini-chess-game.png" class="glow-gold" alt="">
        </div>
        <div class="col-md-8 text-center" data-aos="fade-left" data-aos-duration="1300">
            <h1 class="my-5">Checkmate Tycoon 🏆</h1>
            <h3>🔰 Conquer with best players</h3>
            <h3>🔰 Learn best tactics</h3>
            <h3>🔰 Win biggest prises</h3>


        </div>
    </div>
    <div class="row p-3 justify-content-center">
        <div class="col-md-8">
            <div class="card" data-aos="flip-up" data-aos-duration="900">
                <!-- <img src="static/img/Chess Pieces/BlackQueen.png" class="card-img-top" alt="..."> -->
                <h1>CONNECT WITH
                    AMBITIOUS PLAYERS</h1>
                <p>Society is influencing you for society's well being.</p>
                <p>They don't want you to be free, they want slaves who work, consume and die.</p>
                <p><b>Here you will learn the truth about life.</b></p>
                <p>Here you will learn how to become free.</p>
                <a class="btn button-dark d-block" href="/register">
                    <h3>Register</h3>
                </a>
            </div>
        </div>
    </div>



</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}
  <meta charset="UTF-8">
  <title>Chess of Fortune ♟️</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="static/styles/jquery-ui.css">
  <link rel="stylesheet" href="static/styles/jquery-ui.structure.css">
  <link rel="stylesheet" href="static/styles/jquery-ui.theme.css">
  <link rel="stylesheet" href="static/styles/style.css">
  <link rel="stylesheet" href="static/styles/nav.css">
  <!-- Bs5 Icons  -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <!-- Animation Library  -->
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  {% endblock %}
</head>

<body>
  {% block navbar %}
  {% include "header.html" %}
  {% endblock %}

  {% block flash %}

  {% endblock %}

  {% block content %}

  {% endblock %}

  {% block footer %}
  {% include "footer.html" %}
  {% endblock %}
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="static/js/jquery.js"></script>
<script src="static/js/jquery-ui.js"></script>
<!-- Animation JS  -->
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
  AOS.init();
</script>
{% block js %}

{% endblock %}

</html>

templates/login.html
{% extends "layout.html" %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
{{ super() }}
{% endblock %}

{% block flash %}
<section id="flash">
    {% with items=get_flashed_messages() %}
    <div>
        <ul>
            {% for item in items %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endwith %}
</section>
{% endblock %}

{% block content %}
<div class="cointainter">
    <section id="log">

        <div class="row text-center mt-5">
            <h1>Log In</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-4">

                <div class="card">

                    <form action="{{url_for('users_bp.login')}}" method="post">
                        {{ login_form.csrf_token }}
                        <div class="form-group">
                            <h5>{{login_form.username.label}}
                                {{login_form.username(class_="form-control", size=30)}}
                            </h5>
                        </div>
                        <div class="form-group mt-1">
                            <h5>
                                {{login_form.password.label}} 
                                {{login_form.password(class_="form-control", size=30)}}
                            </h5>
                        </div>
                        <div>
                            {{login_form.submit(class_="form-control btn button w-100 mt-4", size=10)}}
                        </div>
                    </form>
                    <div class="row text-center">
                        <span class="mt-3 ">
                            Dont have an account? <a href="{{url_for('users_bp.register')}}">Register</a>    
                        </span>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>

{% endblock %}

templates/register.html
{% extends "layout.html" %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block navbar %}
    {{ super() }}
{% endblock %}

{% block flash %}
    <section id="flash">
        {% with items=get_flashed_messages() %}
        <div>
            <ul>
            {% for item in items %}
            <li>{{ item }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endwith %}
    </section>
{% endblock %}

{% block content %}
<div class="cointainter">
    <section id="log">

        <div class="row text-center mt-5">
            <h1>Sign Up</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-4">

                <div class="card">
                    <form action="{{url_for('users_bp.register')}}" method="post">
                        {{ reg_form.csrf_token }}
                        <div class="form-group">
                            <h5>
                                {{reg_form.email.label}} {{reg_form.email(class_="form-control", size=30)}}
                            </h5>
                        </div>
                        <div class="form-group">
                            <h5>
                                {{reg_form.username.label}} {{reg_form.username(class_="form-control", size=30)}}
                            </h5>
                        </div>
                        <div class="form-group">
                            <h5>
                                {{reg_form.password.label}} {{reg_form.password(class_="form-control", size=30)}}
                            </h5>
                        </div>
                        <div>
                            {{reg_form.submit(class_="form-control btn button w-100 mt-4", size=10)}}
                        </div>
                    </form>
                    <div class="row text-center">
                        <span class="mt-3 ">
                            Already have an account? <a href="{{url_for('users_bp.login')}}">Log In</a>    
                        </span>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>
{% endblock %}